{
    'name': 'School SMS',
    'version': "12.0.1.0.0",
    'author': 'Bahar Ali',
    'website': 'http://www.inovtec.com.pk',
    'category': 'School Management',
    'license': "AGPL-3",
    'summary': 'A Module For SMS Management',
    'complexity': 'easy',
    'images': [],
    'depends': ['school'],
    'data': ['security/sms_security.xml',
             'security/ir.model.access.csv',
             'views/sms_view.xml',
             'views/sms_view_menu.xml'],
    'demo': ['demo/school_sms_demo.xml'],
    'installable': True,
    'application': True,
}
