# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'University',
    'version': '9.0.0.2.2',
    'author': '''Serpent Consulting Services PVT. LTD.,
                Odoo Community Association (OCA)''',
    'website': 'http://www.serpentcs.com',
    'category': 'University Management',
    'license': '',
    'complexity': 'easy',
    'Summary': 'A Module For University Management',
    'depends': ['hr', 'mail', 'crm', 'report', 'board',
                'account_voucher', 'hr_recruitment'],
    'data': [
             'security/school_security.xml',
             'security/school_department_security.xml',
             'security/school_faculty_security.xml',
             'security/school_campus_security.xml',
             'security/school_fees_security.xml',
             'security/ir.model.access.csv',
             'views/template_view.xml',
             'wizard/select_subject_wizard.xml',
             'views/school_view.xml',
             'views/school_dashboard.xml',
             'data/student_sequence.xml',
             'wizard/assign_roll_no_wizard.xml',
             'wizard/move_standards_view.xml',
             'views/report_view.xml',
             'views/identity_card.xml',
             'views/application_form.xml',
             'views/school_teacher_view.xml',
             'views/school_parent_view.xml',
             'views/faculty_view.xml',
             'views/school_campus_manager_view.xml',
             'views/student_admission_letter_report.xml',
             'views/school_department_manager_view.xml',
             'views/school_fees_manager_view.xml',
             'views/school_admission_registrar_view.xml',
             'data/data.xml',
             'data/server_automated_action.xml',
             'data/student_reminder_email_template.xml',
             ],
    'demo': ['demo/school_demo.xml'],
    'test': ['test/school_test.yml',
             'test/assign_roll_no_test.yml'],
    'qweb': [
        "static/src/xml/school_dashboard.xml",
    ],
    'installable': True,
    'application': True
}
